---
commitizen:
  annotated_tag: true
  bump_message: 'chore(bump): version $current_version -> $new_version'
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: "0.0.1"
  version_files:
  - cmd/root.go:Version
  version_provider: commitizen
  version_scheme: semver2
