name: go
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup go environment
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"
          check-latest: true
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...
